import { describe, it, expect, afterEach } from "vitest";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import { assembleAuditReport } from "../../../scripts/reports/audit-report.js";
import {
  createTestProject,
  copyFixture,
  type TestProject,
} from "../../helpers.js";

let project: TestProject | null = null;

afterEach(async () => {
  if (project) {
    await project.cleanup();
    project = null;
  }
});

describe("assembleAuditReport", () => {
  it("produces a report with header and severity counts", async () => {
    project = await createTestProject();
    await copyFixture("src_api.json", project.modulesDir);
    await copyFixture("src_auth.json", project.modulesDir);

    await assembleAuditReport(project.projectRoot);

    const report = await readFile(
      join(project.reportsDir, "AUDIT_REPORT.md"),
      "utf-8",
    );
    expect(report).toContain("# Audit Report");
    expect(report).toContain("Total findings:");
    expect(report).toContain("critical");
    expect(report).toContain("warning");
  });

  it("includes a summary table when issues exist", async () => {
    project = await createTestProject();
    await copyFixture("src_api.json", project.modulesDir);

    await assembleAuditReport(project.projectRoot);

    const report = await readFile(
      join(project.reportsDir, "AUDIT_REPORT.md"),
      "utf-8",
    );
    expect(report).toContain("## Summary");
    expect(report).toContain("| Severity |");
    expect(report).toContain("| --- |");
  });

  it("includes the cross-module placeholder comment", async () => {
    project = await createTestProject();

    await assembleAuditReport(project.projectRoot);

    const report = await readFile(
      join(project.reportsDir, "AUDIT_REPORT.md"),
      "utf-8",
    );
    expect(report).toContain("<!-- CROSS_MODULE_PLACEHOLDER -->");
  });

  it("includes the report footer", async () => {
    project = await createTestProject();

    await assembleAuditReport(project.projectRoot);

    const report = await readFile(
      join(project.reportsDir, "AUDIT_REPORT.md"),
      "utf-8",
    );
    expect(report).toContain("Generated by repo-audit");
  });

  it("handles empty project (no modules)", async () => {
    project = await createTestProject();

    await assembleAuditReport(project.projectRoot);

    const report = await readFile(
      join(project.reportsDir, "AUDIT_REPORT.md"),
      "utf-8",
    );
    expect(report).toContain("# Audit Report");
    expect(report).toContain("Total findings:** 0");
  });

  it("includes systemic patterns from variant-analysis.json", async () => {
    project = await createTestProject();
    await copyFixture("src_api.json", project.modulesDir);

    await writeFile(
      join(project.dataDir, "variant-analysis.json"),
      JSON.stringify({
        systemic_patterns: {
          "SEC-005-rate-limit-auth": {
            count: 3,
            files: ["a.py", "b.py", "c.py"],
            directories: ["src_api", "src_auth", "src_utils"],
            severity: "warning",
            category: "security",
          },
        },
        single_critical: {},
        category_distribution: {},
        total_high_severity: 3,
      }),
    );

    await assembleAuditReport(project.projectRoot);

    const report = await readFile(
      join(project.reportsDir, "AUDIT_REPORT.md"),
      "utf-8",
    );
    expect(report).toContain("Systemic Patterns");
    expect(report).toContain("SEC-005-rate-limit-auth");
    expect(report).toContain("3 instances");
  });

  it("lists findings grouped by severity", async () => {
    project = await createTestProject();
    await copyFixture("src_api.json", project.modulesDir);

    await assembleAuditReport(project.projectRoot);

    const report = await readFile(
      join(project.reportsDir, "AUDIT_REPORT.md"),
      "utf-8",
    );
    expect(report).toContain("Findings by Severity");
    expect(report).toContain("Critical Findings");
  });

  it("includes tool results section", async () => {
    project = await createTestProject();

    await assembleAuditReport(project.projectRoot);

    const report = await readFile(
      join(project.reportsDir, "AUDIT_REPORT.md"),
      "utf-8",
    );
    expect(report).toContain("## Tools That Ran");
  });
});
