#!/usr/bin/env bash
# Tests for fill-cross-module-placeholders.sh

set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SCRIPT_UNDER_TEST="${REPO_ROOT}/scripts/fill-cross-module-placeholders.sh"

PASS_COUNT=0
FAIL_COUNT=0
TMPDIR=""

cleanup() {
  [ -n "$TMPDIR" ] && rm -rf "$TMPDIR"
}
trap cleanup EXIT

assert_eq() {
  local desc="$1" expected="$2" actual="$3"
  if [ "$expected" = "$actual" ]; then
    echo "  PASS: $desc"
    PASS_COUNT=$((PASS_COUNT + 1))
  else
    echo "  FAIL: $desc"
    echo "    expected: $expected"
    echo "    actual:   $actual"
    FAIL_COUNT=$((FAIL_COUNT + 1))
  fi
}

assert_contains() {
  local desc="$1" needle="$2" haystack="$3"
  if echo "$haystack" | grep -q "$needle"; then
    echo "  PASS: $desc"
    PASS_COUNT=$((PASS_COUNT + 1))
  else
    echo "  FAIL: $desc"
    echo "    expected to contain: $needle"
    echo "    actual: $haystack"
    FAIL_COUNT=$((FAIL_COUNT + 1))
  fi
}

assert_not_contains() {
  local desc="$1" needle="$2" haystack="$3"
  if echo "$haystack" | grep -q "$needle"; then
    echo "  FAIL: $desc"
    echo "    expected NOT to contain: $needle"
    echo "    actual: $haystack"
    FAIL_COUNT=$((FAIL_COUNT + 1))
  else
    echo "  PASS: $desc"
    PASS_COUNT=$((PASS_COUNT + 1))
  fi
}

# Helper to set up a project dir with reports containing placeholders
setup_project_with_placeholders() {
  TMPDIR=$(mktemp -d)
  mkdir -p "$TMPDIR/sdlc-audit/reports"
  mkdir -p "$TMPDIR/sdlc-audit/data"

  # AUDIT_REPORT.md with placeholder
  cat > "$TMPDIR/sdlc-audit/reports/AUDIT_REPORT.md" <<'REPORT'
# Audit Report

**Total findings: 5** (1 critical, 2 warning, 2 info)

## Critical Findings (1)

- **src/auth.js**: Hardcoded secret

<!-- CROSS_MODULE_PLACEHOLDER -->

---
*Generated by repo-audit*
REPORT

  # TECH_DEBT.md with placeholders
  cat > "$TMPDIR/sdlc-audit/reports/TECH_DEBT.md" <<'REPORT'
# Tech Debt Backlog

**10 issues** identified, prioritized by effort and impact.

## Strategic Improvements
*Medium effort, high impact — plan these into sprints.*

<!-- DRY_VIOLATIONS_PLACEHOLDER -->

- **src/utils.js** (maintainability): Long function

## Major Refactors
*Large effort, high impact — plan carefully.*

<!-- ARCHITECTURE_ISSUES_PLACEHOLDER -->

- **src/core.js** (architecture): God module

---
*Generated by repo-audit*
REPORT

  # DEPENDENCY_GRAPH.md with placeholder
  cat > "$TMPDIR/sdlc-audit/reports/DEPENDENCY_GRAPH.md" <<'REPORT'
# Dependency Graph

**5 modules**, 10 external dependencies, 1 circular dependency

## Internal Dependencies

```
src/auth → src/utils [in:0 out:1]
```

<!-- DEP_GRAPH_INTERPRETATION_PLACEHOLDER -->

---
*Generated by repo-audit*
REPORT

  # TEST_COVERAGE_MAP.md with placeholder
  cat > "$TMPDIR/sdlc-audit/reports/TEST_COVERAGE_MAP.md" <<'REPORT'
# Test Coverage Map

## Coverage by Module

| Module | Coverage |
|--------|----------|
| src/auth | none |

<!-- COVERAGE_GAPS_PLACEHOLDER -->

---
*Generated by repo-audit*
REPORT
}

# Helper to create cross-module JSON files
create_cross_module_data() {
  local data_dir="$TMPDIR/sdlc-audit/data"

  cat > "$data_dir/cross-module-dry.json" <<'JSON'
{
  "duplications": [
    {
      "description": "Config parsing duplicated",
      "locations": ["src/auth/config.js", "src/api/config.js"],
      "suggestion": "Extract shared config parser into src/common/config.js"
    },
    {
      "description": "Validation logic repeated",
      "locations": ["src/users/validate.js", "src/orders/validate.js", "src/products/validate.js"],
      "suggestion": "Create a shared validation module"
    }
  ]
}
JSON

  cat > "$data_dir/cross-module-inconsistencies.json" <<'JSON'
{
  "inconsistencies": [
    {
      "pattern_type": "Error handling",
      "description": "Mix of throw and return-error patterns",
      "examples": ["src/auth throws", "src/api returns errors"],
      "recommendation": "Standardize on throw with try-catch"
    }
  ]
}
JSON

  cat > "$data_dir/cross-module-architecture.json" <<'JSON'
{
  "architecture_issues": [
    {
      "type": "God module",
      "description": "src/core handles too many responsibilities",
      "affected_modules": ["src/core", "src/auth", "src/api"],
      "suggestion": "Split into domain-specific modules"
    }
  ],
  "dependency_interpretation": {
    "problematic_cycles": [
      {
        "cycle": ["src/auth", "src/core", "src/auth"],
        "reason": "Auth depends on core for config, core depends on auth for middleware"
      }
    ],
    "hub_assessment": [
      {
        "module": "src/core",
        "assessment": "High fan-in is justified as shared utilities but should be split"
      }
    ],
    "decoupling_suggestions": [
      "Extract config from src/core into a standalone module",
      "Use dependency injection for auth middleware"
    ]
  },
  "duplicate_externals": [
    {
      "package": "lodash",
      "issue": "Used in 4 modules but only for _.get — replace with optional chaining"
    }
  ]
}
JSON

  cat > "$data_dir/cross-module-coverage.json" <<'JSON'
{
  "test_gaps": [
    {
      "module": "src/auth",
      "priority": 1,
      "description": "No tests for authentication module",
      "risk_note": "Highest risk module with no coverage"
    },
    {
      "module": "src/payments",
      "priority": 2,
      "description": "No tests for payment processing",
      "risk_note": "Financial operations need thorough testing"
    }
  ]
}
JSON
}

# ======================================================================
# Test 1: Placeholders filled with cross-module data
# ======================================================================
echo "=== Test 1: Placeholders filled with cross-module data ==="
setup_project_with_placeholders
create_cross_module_data

bash "$SCRIPT_UNDER_TEST" "$TMPDIR" >/dev/null 2>&1
EXIT_CODE=$?

assert_eq "Exit code is 0" "0" "$EXIT_CODE"

# Check AUDIT_REPORT.md
AUDIT_CONTENT=$(cat "$TMPDIR/sdlc-audit/reports/AUDIT_REPORT.md")
assert_not_contains "Placeholder removed from audit report" "CROSS_MODULE_PLACEHOLDER" "$AUDIT_CONTENT"
assert_contains "Audit report has Cross-Module Analysis" "Cross-Module Analysis" "$AUDIT_CONTENT"
assert_contains "Audit report has DRY Violations" "DRY Violations" "$AUDIT_CONTENT"
assert_contains "Audit report has config parsing duplication" "Config parsing duplicated" "$AUDIT_CONTENT"
assert_contains "Audit report has Inconsistencies" "Inconsistencies" "$AUDIT_CONTENT"
assert_contains "Audit report has error handling inconsistency" "Error handling" "$AUDIT_CONTENT"
assert_contains "Audit report has Architecture Issues" "Architecture Issues" "$AUDIT_CONTENT"
assert_contains "Audit report has god module issue" "God module" "$AUDIT_CONTENT"
assert_contains "Audit report preserves footer" "Generated by repo-audit" "$AUDIT_CONTENT"

# Check TECH_DEBT.md
DEBT_CONTENT=$(cat "$TMPDIR/sdlc-audit/reports/TECH_DEBT.md")
assert_not_contains "DRY placeholder removed from tech debt" "DRY_VIOLATIONS_PLACEHOLDER" "$DEBT_CONTENT"
assert_not_contains "Arch placeholder removed from tech debt" "ARCHITECTURE_ISSUES_PLACEHOLDER" "$DEBT_CONTENT"
assert_contains "Tech debt has cross-module DRY violations" "Cross-Module DRY Violations" "$DEBT_CONTENT"
assert_contains "Tech debt has config parsing" "Config parsing duplicated" "$DEBT_CONTENT"
assert_contains "Tech debt has cross-module architecture issues" "Cross-Module Architecture Issues" "$DEBT_CONTENT"
assert_contains "Tech debt has god module" "God module" "$DEBT_CONTENT"
assert_contains "Tech debt preserves existing content" "Long function" "$DEBT_CONTENT"

# Check DEPENDENCY_GRAPH.md
DEP_CONTENT=$(cat "$TMPDIR/sdlc-audit/reports/DEPENDENCY_GRAPH.md")
assert_not_contains "Dep graph placeholder removed" "DEP_GRAPH_INTERPRETATION_PLACEHOLDER" "$DEP_CONTENT"
assert_contains "Dep graph has interpretation section" "Dependency Interpretation" "$DEP_CONTENT"
assert_contains "Dep graph has problematic cycles" "Problematic Cycles" "$DEP_CONTENT"
assert_contains "Dep graph has hub assessment" "Hub Assessment" "$DEP_CONTENT"
assert_contains "Dep graph has decoupling suggestions" "Decoupling Suggestions" "$DEP_CONTENT"
assert_contains "Dep graph has duplicate externals" "Duplicate External Dependencies" "$DEP_CONTENT"
assert_contains "Dep graph has lodash issue" "lodash" "$DEP_CONTENT"

# Check TEST_COVERAGE_MAP.md
COV_CONTENT=$(cat "$TMPDIR/sdlc-audit/reports/TEST_COVERAGE_MAP.md")
assert_not_contains "Coverage placeholder removed" "COVERAGE_GAPS_PLACEHOLDER" "$COV_CONTENT"
assert_contains "Coverage has gap analysis" "Coverage Gap Analysis" "$COV_CONTENT"
assert_contains "Coverage has auth gap" "src/auth" "$COV_CONTENT"
assert_contains "Coverage has payments gap" "src/payments" "$COV_CONTENT"
assert_contains "Coverage has risk note" "Highest risk module" "$COV_CONTENT"

rm -rf "$TMPDIR"
TMPDIR=""

# ======================================================================
# Test 2: Placeholders removed when no cross-module data exists
# ======================================================================
echo "=== Test 2: Placeholders removed when no cross-module data ==="
setup_project_with_placeholders
# No cross-module JSON files created

bash "$SCRIPT_UNDER_TEST" "$TMPDIR" >/dev/null 2>&1
EXIT_CODE=$?

assert_eq "Exit code is 0" "0" "$EXIT_CODE"

# All placeholders should be gone
AUDIT_CONTENT=$(cat "$TMPDIR/sdlc-audit/reports/AUDIT_REPORT.md")
assert_not_contains "CROSS_MODULE placeholder removed" "CROSS_MODULE_PLACEHOLDER" "$AUDIT_CONTENT"
assert_not_contains "No cross-module section added" "Cross-Module Analysis" "$AUDIT_CONTENT"
assert_contains "Audit report still has original content" "Hardcoded secret" "$AUDIT_CONTENT"
assert_contains "Audit report still has footer" "Generated by repo-audit" "$AUDIT_CONTENT"

DEBT_CONTENT=$(cat "$TMPDIR/sdlc-audit/reports/TECH_DEBT.md")
assert_not_contains "DRY placeholder removed" "DRY_VIOLATIONS_PLACEHOLDER" "$DEBT_CONTENT"
assert_not_contains "Arch placeholder removed" "ARCHITECTURE_ISSUES_PLACEHOLDER" "$DEBT_CONTENT"
assert_contains "Tech debt still has original content" "Long function" "$DEBT_CONTENT"

DEP_CONTENT=$(cat "$TMPDIR/sdlc-audit/reports/DEPENDENCY_GRAPH.md")
assert_not_contains "Dep placeholder removed" "DEP_GRAPH_INTERPRETATION_PLACEHOLDER" "$DEP_CONTENT"
assert_contains "Dep graph still has original content" "Internal Dependencies" "$DEP_CONTENT"

COV_CONTENT=$(cat "$TMPDIR/sdlc-audit/reports/TEST_COVERAGE_MAP.md")
assert_not_contains "Coverage placeholder removed" "COVERAGE_GAPS_PLACEHOLDER" "$COV_CONTENT"
assert_contains "Coverage still has original content" "Coverage by Module" "$COV_CONTENT"

rm -rf "$TMPDIR"
TMPDIR=""

# ======================================================================
# Test 3: No reports exist — exits cleanly
# ======================================================================
echo "=== Test 3: No reports exist — exits cleanly ==="
TMPDIR=$(mktemp -d)
mkdir -p "$TMPDIR/sdlc-audit/data"
mkdir -p "$TMPDIR/sdlc-audit/reports"
# No report files

bash "$SCRIPT_UNDER_TEST" "$TMPDIR" >/dev/null 2>&1
EXIT_CODE=$?

assert_eq "Exit code is 0 with no reports" "0" "$EXIT_CODE"

rm -rf "$TMPDIR"
TMPDIR=""

# ======================================================================
# Test 4: Empty cross-module arrays do not insert content
# ======================================================================
echo "=== Test 4: Empty cross-module arrays ==="
setup_project_with_placeholders

# Create cross-module files with empty arrays
cat > "$TMPDIR/sdlc-audit/data/cross-module-dry.json" <<'JSON'
{"duplications": []}
JSON
cat > "$TMPDIR/sdlc-audit/data/cross-module-architecture.json" <<'JSON'
{"architecture_issues": [], "dependency_interpretation": {"problematic_cycles": [], "hub_assessment": [], "decoupling_suggestions": []}, "duplicate_externals": []}
JSON
cat > "$TMPDIR/sdlc-audit/data/cross-module-coverage.json" <<'JSON'
{"test_gaps": []}
JSON

bash "$SCRIPT_UNDER_TEST" "$TMPDIR" >/dev/null 2>&1
EXIT_CODE=$?

assert_eq "Exit code is 0 with empty arrays" "0" "$EXIT_CODE"

AUDIT_CONTENT=$(cat "$TMPDIR/sdlc-audit/reports/AUDIT_REPORT.md")
assert_not_contains "No placeholder left with empty data" "CROSS_MODULE_PLACEHOLDER" "$AUDIT_CONTENT"
assert_not_contains "No cross-module section with empty data" "Cross-Module Analysis" "$AUDIT_CONTENT"

DEBT_CONTENT=$(cat "$TMPDIR/sdlc-audit/reports/TECH_DEBT.md")
assert_not_contains "No DRY placeholder with empty data" "DRY_VIOLATIONS_PLACEHOLDER" "$DEBT_CONTENT"
assert_not_contains "No arch placeholder with empty data" "ARCHITECTURE_ISSUES_PLACEHOLDER" "$DEBT_CONTENT"

rm -rf "$TMPDIR"
TMPDIR=""

# ======================================================================
# Test 5: Partial cross-module data (only some files exist)
# ======================================================================
echo "=== Test 5: Partial cross-module data ==="
setup_project_with_placeholders

# Only create DRY violations — no architecture, inconsistencies, or coverage
cat > "$TMPDIR/sdlc-audit/data/cross-module-dry.json" <<'JSON'
{
  "duplications": [
    {
      "description": "Logger setup repeated",
      "locations": ["src/api/logger.js", "src/worker/logger.js"],
      "suggestion": "Use shared logger module"
    }
  ]
}
JSON

bash "$SCRIPT_UNDER_TEST" "$TMPDIR" >/dev/null 2>&1
EXIT_CODE=$?

assert_eq "Exit code is 0 with partial data" "0" "$EXIT_CODE"

# Audit report should have DRY violations but no inconsistencies or architecture
AUDIT_CONTENT=$(cat "$TMPDIR/sdlc-audit/reports/AUDIT_REPORT.md")
assert_contains "Has cross-module section with partial data" "Cross-Module Analysis" "$AUDIT_CONTENT"
assert_contains "Has DRY violations" "Logger setup repeated" "$AUDIT_CONTENT"
assert_not_contains "No inconsistencies section" "Inconsistencies" "$AUDIT_CONTENT"
assert_not_contains "No architecture section" "Architecture Issues" "$AUDIT_CONTENT"

# Tech debt should have DRY filled but architecture placeholder removed
DEBT_CONTENT=$(cat "$TMPDIR/sdlc-audit/reports/TECH_DEBT.md")
assert_contains "Tech debt has DRY content" "Logger setup repeated" "$DEBT_CONTENT"
assert_not_contains "Tech debt arch placeholder removed" "ARCHITECTURE_ISSUES_PLACEHOLDER" "$DEBT_CONTENT"
assert_not_contains "No arch content without arch file" "Cross-Module Architecture" "$DEBT_CONTENT"

# Dep graph placeholder should be removed (no arch file)
DEP_CONTENT=$(cat "$TMPDIR/sdlc-audit/reports/DEPENDENCY_GRAPH.md")
assert_not_contains "Dep placeholder removed without arch file" "DEP_GRAPH_INTERPRETATION_PLACEHOLDER" "$DEP_CONTENT"

# Coverage placeholder should be removed (no coverage file)
COV_CONTENT=$(cat "$TMPDIR/sdlc-audit/reports/TEST_COVERAGE_MAP.md")
assert_not_contains "Coverage placeholder removed without coverage file" "COVERAGE_GAPS_PLACEHOLDER" "$COV_CONTENT"

rm -rf "$TMPDIR"
TMPDIR=""

# ======================================================================
# Summary
# ======================================================================
echo ""
echo "fill-cross-module-placeholders: ${PASS_COUNT} passed, ${FAIL_COUNT} failed"

[ "$FAIL_COUNT" -eq 0 ] || exit 1
