/**
 * Shared utilities for report assemblers.
 *
 * Provides markdown formatting helpers used by all report generators.
 */

/**
 * Build a markdown table from headers and rows.
 * Columns are pipe-separated with a header separator row.
 */
export function markdownTable(
  headers: string[],
  rows: string[][],
): string {
  const headerLine = `| ${headers.join(" | ")} |`;
  const separator = `| ${headers.map(() => "---").join(" | ")} |`;
  const bodyLines = rows.map((row) => `| ${row.join(" | ")} |`);
  return [headerLine, separator, ...bodyLines].join("\n");
}

/**
 * Wrap content in a markdown section with a heading.
 */
export function markdownSection(
  level: number,
  title: string,
  content: string,
): string {
  const prefix = "#".repeat(level);
  return `${prefix} ${title}\n\n${content}`;
}

/**
 * Format a list of items as a markdown bullet list.
 */
export function bulletList(items: string[]): string {
  if (items.length === 0) return "None found.";
  return items.map((item) => `- ${item}`).join("\n");
}

/**
 * Read and parse a JSON file, returning null on any error.
 */
export async function safeReadJson<T>(
  readFile: (path: string, enc: BufferEncoding) => Promise<string>,
  path: string,
): Promise<T | null> {
  try {
    const raw = await readFile(path, "utf-8");
    return JSON.parse(raw) as T;
  } catch {
    return null;
  }
}

/** Standard report footer. */
export const REPORT_FOOTER = "\n---\n*Generated by repo-audit*\n";
