#!/usr/bin/env bash
# repo-audit: Assemble DEPENDENCY_GRAPH.md from dependency-data.json.
#
# Formats the programmatic dependency graph as a readable markdown document
# with arrows, cycle highlighting, hub/orphan flags, and external dep inventory.
#
# Requires: jq
# Usage: bash assemble-dep-graph.sh [project-root]
# Output: sdlc-audit/reports/DEPENDENCY_GRAPH.md

set -o pipefail

PROJECT_ROOT="${1:-.}"
DATA_DIR="${PROJECT_ROOT}/sdlc-audit/data"
DEP_FILE="${DATA_DIR}/dependency-data.json"
OUTPUT_DIR="${PROJECT_ROOT}/sdlc-audit/reports"
OUTPUT_FILE="${OUTPUT_DIR}/DEPENDENCY_GRAPH.md"

if [ ! -f "$DEP_FILE" ]; then
  echo "dependency-data.json not found — skipping dependency graph report."
  exit 0
fi

mkdir -p "$OUTPUT_DIR"

{
  echo "# Dependency Graph"
  echo ""

  MODULE_COUNT=$(jq '.module_graph | keys | length' "$DEP_FILE" 2>/dev/null)
  MODULE_COUNT="${MODULE_COUNT:-0}"
  CYCLE_COUNT=$(jq '.circular_dependencies | length' "$DEP_FILE" 2>/dev/null)
  CYCLE_COUNT="${CYCLE_COUNT:-0}"
  HUB_COUNT=$(jq '.hub_modules | length' "$DEP_FILE" 2>/dev/null)
  HUB_COUNT="${HUB_COUNT:-0}"
  ORPHAN_COUNT=$(jq '.orphan_modules | length' "$DEP_FILE" 2>/dev/null)
  ORPHAN_COUNT="${ORPHAN_COUNT:-0}"
  EXT_COUNT=$(jq '.external_dependencies | keys | length' "$DEP_FILE" 2>/dev/null)
  EXT_COUNT="${EXT_COUNT:-0}"

  echo "**${MODULE_COUNT} modules**, ${EXT_COUNT} external dependencies, ${CYCLE_COUNT} circular dependencies"
  echo ""

  # --- Module dependency map ---
  echo "## Internal Dependencies"
  echo ""
  echo '```'
  jq -r '
    .module_graph | to_entries | sort_by(.key) | .[] |
    .key + (
      if ((.value.depends_on // []) | length) > 0
      then " → " + ((.value.depends_on // []) | join(", "))
      else " (leaf)"
      end
    ) + " [in:" + ((.value.fan_in // 0) | tostring) + " out:" + ((.value.fan_out // 0) | tostring) + "]"
  ' "$DEP_FILE" 2>/dev/null
  echo '```'
  echo ""

  # --- Circular dependencies ---
  if [ "$CYCLE_COUNT" -gt 0 ]; then
    echo "## Circular Dependencies"
    echo ""
    echo "**${CYCLE_COUNT} cycles detected** — these create tight coupling and make"
    echo "modules harder to test and refactor independently."
    echo ""
    jq -r '.circular_dependencies[] | "- " + join(" → ")' "$DEP_FILE" 2>/dev/null
    echo ""
  fi

  # --- Hub modules ---
  if [ "$HUB_COUNT" -gt 0 ]; then
    echo "## Hub Modules"
    echo ""
    echo "These modules have unusually high fan-in (many other modules depend on them)."
    echo "Changes here have a large blast radius."
    echo ""
    jq -r '
      .hub_modules[] as $hub |
      .module_graph[$hub] |
      "- **" + $hub + "** — " + ((.fan_in // 0) | tostring) +
      " dependents: " + ((.depended_on_by // []) | join(", "))
    ' "$DEP_FILE" 2>/dev/null
    echo ""
  fi

  # --- Orphan modules ---
  if [ "$ORPHAN_COUNT" -gt 0 ]; then
    echo "## Orphan Modules"
    echo ""
    echo "These modules depend on others but nothing depends on them."
    echo "They may be entry points, or they may be dead code."
    echo ""
    jq -r '.orphan_modules[] | "- " + .' "$DEP_FILE" 2>/dev/null
    echo ""
  fi

  # --- External dependencies ---
  echo "## External Dependencies"
  echo ""
  echo "| Package | Used by |"
  echo "|---------|---------|"
  jq -r '
    .external_dependencies | to_entries |
    sort_by(.value | length) | reverse | .[] |
    "| " + .key + " | " + ((.value // []) | join(", ")) + " |"
  ' "$DEP_FILE" 2>/dev/null
  echo ""

  # --- Duplicate externals (potential conflicts) ---
  echo "## Potential Duplicate Dependencies"
  echo ""
  echo "External packages used by 3+ modules (potential for centralization):"
  echo ""
  jq -r '
    .external_dependencies | to_entries |
    map(select(.value | length >= 3)) |
    sort_by(.value | length) | reverse | .[] |
    "- **" + .key + "** — used by " + (.value | length | tostring) +
    " modules: " + (.value | join(", "))
  ' "$DEP_FILE" 2>/dev/null
  SHARED=$(jq '[.external_dependencies | to_entries[] | select(.value | length >= 3)] | length' "$DEP_FILE" 2>/dev/null)
  SHARED="${SHARED:-0}"
  if [ "$SHARED" = "0" ]; then
    echo "None found."
  fi
  echo ""

  echo ""
  echo "<!-- DEP_GRAPH_INTERPRETATION_PLACEHOLDER -->"
  echo ""

  # --- Footer ---
  echo "---"
  echo "*Generated by repo-audit*"

} > "$OUTPUT_FILE"

echo "Wrote: ${OUTPUT_FILE}"

exit 0
