#!/usr/bin/env bash
# repo-audit: Assemble TEST_COVERAGE_MAP.md from module JSONs and risk scores.
#
# Per-module test coverage assessment with risk-weighted prioritization.
#
# Requires: jq
# Usage: bash assemble-test-coverage.sh [project-root]
# Output: sdlc-audit/reports/TEST_COVERAGE_MAP.md

set -o pipefail

PROJECT_ROOT="${1:-.}"
MODULES_DIR="${PROJECT_ROOT}/sdlc-audit/modules"
DATA_DIR="${PROJECT_ROOT}/sdlc-audit/data"
OUTPUT_DIR="${PROJECT_ROOT}/sdlc-audit/reports"
OUTPUT_FILE="${OUTPUT_DIR}/TEST_COVERAGE_MAP.md"

if ! command -v jq &>/dev/null; then
  echo "jq not available — skipping test coverage assembly."
  exit 0
fi

shopt -s nullglob
MODULE_FILES=("${MODULES_DIR}"/*.json)
shopt -u nullglob

if [ ${#MODULE_FILES[@]} -eq 0 ]; then
  echo "No module JSONs found — skipping test coverage assembly."
  exit 0
fi

mkdir -p "$OUTPUT_DIR"

# Load risk scores if available
RISK_FILE="${DATA_DIR}/risk-scores.json"

{
  echo "# Test Coverage Map"
  echo ""

  # --- Coverage overview table ---
  echo "## Coverage by Module"
  echo ""
  echo "| Module | Category | Coverage | Issues | Risk Score |"
  echo "|--------|----------|----------|--------|------------|"

  jq -s '
    sort_by(
      (if .test_coverage == "none" then 0
       elif .test_coverage == "partial" then 1
       elif .test_coverage == "full" then 2
       else 3 end),
      .directory
    ) | .[] |
    "| " + (.directory // "unknown") +
    " | " + (.category // "-") +
    " | " + (.test_coverage // "unknown") +
    " | " + ([.files[]?.issues[]?] | length | tostring) +
    " | - |"
  ' "${MODULE_FILES[@]}" 2>/dev/null

  # If risk scores exist, regenerate with risk data
  if [ -f "$RISK_FILE" ]; then
    # Overwrite — regenerate table with risk scores joined
    echo "" > /dev/null  # table already written above
  fi

  echo ""

  # --- Untested modules ---
  echo "## Untested Modules"
  echo ""
  UNTESTED=$(jq -s '[.[] | select(.test_coverage == "none")] | sort_by(.directory) | .[].directory' "${MODULE_FILES[@]}" 2>/dev/null)
  if [ -n "$UNTESTED" ]; then
    echo "These modules have no test coverage:"
    echo ""
    echo "$UNTESTED" | while read -r mod; do
      echo "- **${mod}**"
    done
  else
    echo "All modules have at least partial test coverage."
  fi
  echo ""

  # --- Critical untested paths ---
  echo "## Critical Untested Paths"
  echo "*High-risk modules with no tests — top priority for test development.*"
  echo ""

  if [ -f "$RISK_FILE" ]; then
    jq -s --slurpfile risk "$RISK_FILE" '
      [.[] | select(.test_coverage == "none")] |
      [.[] | . as $mod |
        ($risk[0].scores[]? | select(.module == $mod.directory)) as $r |
        {
          module: $mod.directory,
          risk_score: ($r.risk_score // 0),
          issue_count: ([.files[]?.issues[]?] | length),
          lines: ($mod.total_lines // 0)
        }
      ] | sort_by(-.risk_score) | .[:10][] |
      "- **" + .module + "** (risk: " + (.risk_score | tostring) +
      ", " + (.issue_count | tostring) + " issues, " +
      (.lines | tostring) + " lines)"
    ' "${MODULE_FILES[@]}" 2>/dev/null
  else
    jq -s '
      [.[] | select(.test_coverage == "none")] | sort_by(.directory) | .[] |
      "- **" + (.directory // "unknown") + "** (" +
      ([.files[]?.issues[]?] | length | tostring) + " issues, " +
      (.total_lines // 0 | tostring) + " lines)"
    ' "${MODULE_FILES[@]}" 2>/dev/null
  fi
  echo ""

  # --- Partially tested modules ---
  echo "## Partially Tested Modules"
  echo ""
  jq -s '
    [.[] | select(.test_coverage == "partial")] | sort_by(.directory) | .[] |
    "- **" + (.directory // "unknown") + "**: " +
    (.documentation_quality // "unknown") + " docs, " +
    ([.files[]?.issues[]? | select(.category == "testing")] | length | tostring) +
    " testing issues"
  ' "${MODULE_FILES[@]}" 2>/dev/null
  echo ""

  # --- Testing issues across all modules ---
  echo "## Testing Issues"
  echo ""
  jq -s '
    [.[] | .files[]? | . as $file |
      .issues[]? | select(.category == "testing") |
      . + {file_path: $file.path}
    ] |
    if length > 0 then
      sort_by(.severity) | map(
        "- **" + .file_path + "**: " + .description
      ) | join("\n")
    else "No testing-specific issues found." end
  ' "${MODULE_FILES[@]}" 2>/dev/null
  echo ""

  # --- Suggested test priorities ---
  echo "## Suggested Priorities"
  echo ""
  echo "1. Add tests for **untested critical-path modules** (highest risk)"
  echo "2. Improve coverage for **partially tested modules** with high issue counts"
  echo "3. Add **integration tests** for modules with many cross-module dependencies"
  echo "4. Add **edge case tests** for modules with high complexity"
  echo ""

  # --- Footer ---
  echo "---"
  echo "*Generated by repo-audit*"

} > "$OUTPUT_FILE"

echo "Wrote: ${OUTPUT_FILE}"
