/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NativeScipDocument {
  path: string
  occurrences: number
  definitions: number
  imports: number
  references: number
}
export interface NativeScipSummary {
  toolName: string
  toolVersion: string
  projectRoot: string
  documents: number
  occurrences: number
  definitions: number
  imports: number
  references: number
  relationships: number
  externalSymbols: number
  bytes: number
  sha256: string
  sampleDocuments: Array<NativeScipDocument>
}
export interface NativeStagedSnapshot {
  sourceSignature: string
  files: number
  bytes: number
}
export interface NativeSnapshotEntry {
  path: string
  bytes: number
  sha256: string
}
export interface NativeSnapshotManifest {
  inputSignature: string
  files: number
  bytes: number
  entries: Array<NativeSnapshotEntry>
}
/** Decode and summarize a SCIP protobuf without blocking the Node event loop. */
export declare function inspectScip(path: string): Promise<NativeScipSummary>
/** Copy the indexed source inventory into a private, immutable-for-the-run view. */
export declare function stageSourceSnapshot(root: string, destination: string, expectedSignature: string): Promise<NativeStagedSnapshot>
/** Hash every staged provider input before and after execution. */
export declare function snapshotManifest(root: string): Promise<NativeSnapshotManifest>
export interface NativeSymbol {
  kind: string
  name: string
  startLine: number
  startColumn: number
  endLine: number
  endColumn: number
  exported: boolean
  defaultExport: boolean
  signature: string
}
export interface NativeRef {
  /** The name as the defining module exports it. */
  name: string
  /** The specifier it came from, still unresolved. */
  module: string
  line: number
  column: number
}
export interface NativeFile {
  path: string
  lang: string
  loc: number
  bytes: number
  contentSha: string
  isTest: boolean
  /** False for files no grammar covers, or that were skipped as noise. */
  parsed: boolean
  symbols: Array<NativeSymbol>
  imports: Array<string>
  /** Uses of imported names, for symbol-level reference resolution. */
  refs: Array<NativeRef>
}
export interface NativeScan {
  files: Array<NativeFile>
  walkMs: number
  parseMs: number
}
/** Walk and parse a repository. Both phases use every core, off the event loop. */
export declare function scanRepo(root: string): Promise<NativeScan>
export interface NativeMatch {
  path: string
  line: number
  endLine: number
  /** The captured node's own text, trimmed for display. */
  text: string
  /** Which capture in the query matched, e.g. "@call". */
  capture: string
}
/**
 * Search by code shape rather than by text.
 *
 * A regex finds `catch` and cannot tell an empty handler from a careful one;
 * a tree-sitter query can, because it matches the parsed structure. This is
 * what makes "find every place we swallow an error" a question with an exact
 * answer instead of a grep and a lot of reading.
 *
 * The query is tree-sitter's own S-expression syntax, run against whichever
 * grammar each file needs.
 */
export declare function searchStructural(root: string, query: string, languages?: Array<string> | undefined | null, limit?: number | undefined | null, textFilter?: string | undefined | null): Promise<Array<NativeMatch>>
/** Walk only — used to compare phases against the TypeScript walker. */
export declare function walkRepo(root: string): Promise<Array<NativeFile>>
