/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Current Rust-owned workspace-store schema version.  */
export declare function databaseSchemaVersion(): number
export interface NativeScipDocument {
  path: string
  occurrences: number
  definitions: number
  imports: number
  references: number
}
export interface NativeScipSummary {
  toolName: string
  toolVersion: string
  projectRoot: string
  documents: number
  occurrences: number
  definitions: number
  imports: number
  references: number
  relationships: number
  externalSymbols: number
  bytes: number
  sha256: string
  sampleDocuments: Array<NativeScipDocument>
}
export interface NativeScipRange {
  startLine: number
  startColumn: number
  endLine: number
  endColumn: number
}
export interface NativeScipSourceDocument {
  path: string
  language: string
}
export interface NativeScipPathAlias {
  /** Lexically normalized path emitted by the provider. */
  providerPath: string
  /** Canonical manifest spelling observed while the staged input existed. */
  path: string
}
export interface NativeScipSymbol {
  /** Document-scoped for SCIP local symbols; global otherwise. */
  key: string
  symbol: string
  displayName: string
  kind: string
  path?: string
  external: boolean
  /** Conflicting provider documents or metadata describe this identity. */
  ambiguous: boolean
}
export interface NativeScipOccurrence {
  path: string
  range?: NativeScipRange
  positionEncoding: string
  symbolKey: string
  symbol: string
  /** definition, import, reference, read, or write. */
  kind: string
  /** Lossless SCIP role labels for evidence/debugging. */
  nativeKind: string
  ambiguous: boolean
}
export interface NativeScipRelationship {
  path?: string
  sourceKey: string
  sourceSymbol: string
  targetKey: string
  targetSymbol: string
  /** implement or reference in the provider-neutral vocabulary. */
  kind: string
  /** The exact SCIP relationship flag represented by this edge. */
  nativeKind: string
  ambiguous: boolean
}
export interface NativeScipProjection {
  sha256: string
  pathAliases: Array<NativeScipPathAlias>
  pathAliasSignature: string
  documents: Array<NativeScipSourceDocument>
  symbols: Array<NativeScipSymbol>
  occurrences: Array<NativeScipOccurrence>
  relationships: Array<NativeScipRelationship>
}
export interface NativeStagedSnapshot {
  sourceSignature: string
  files: number
  bytes: number
}
export interface NativeSnapshotEntry {
  path: string
  bytes: number
  sha256: string
}
export interface NativeSnapshotManifest {
  inputSignature: string
  files: number
  bytes: number
  entries: Array<NativeSnapshotEntry>
  pathAliases?: Array<NativeScipPathAlias>
  pathAliasSignature?: string
}
/** Decode and summarize a SCIP protobuf without blocking the Node event loop. */
export declare function inspectScip(path: string): Promise<NativeScipSummary>
/** Decode bounded SCIP occurrences and relationships for neutral fact shaping. */
export declare function projectScip(path: string, expectedSourceRoot: string, pathAliases: Array<NativeScipPathAlias>): Promise<NativeScipProjection>
/** Copy the indexed source inventory into a private, immutable-for-the-run view. */
export declare function stageSourceSnapshot(root: string, destination: string, expectedSignature: string): Promise<NativeStagedSnapshot>
/** Hash every staged provider input before and after execution. */
export declare function snapshotManifest(root: string): Promise<NativeSnapshotManifest>
/** Recompute and validate a durable provider input manifest off the event loop. */
export declare function verifySnapshotManifest(manifest: NativeSnapshotManifest): Promise<boolean>
export interface NativeGitChange {
  path: string
  previousPath?: string
  status: string
  indexStatus: string
  worktreeStatus: string
  worktreePathPresent?: boolean
}
export interface NativeGitChangeSet {
  state: string
  source: string
  changes: Array<NativeGitChange>
  detectedPaths: number
  truncated: boolean
  diagnostic?: string
}
export interface NativeSymbol {
  kind: string
  name: string
  startLine: number
  startColumn: number
  endLine: number
  endColumn: number
  exported: boolean
  defaultExport: boolean
  signature: string
}
export interface NativeRef {
  /** The name as the defining module exports it. */
  name: string
  /** The specifier it came from, still unresolved. */
  module: string
  line: number
  column: number
}
export interface NativeImport {
  specifier: string
  startLine: number
  endLine: number
}
export interface NativeExecutionNode {
  id: string
  ordinal: number
  kind: string
  label: string
  path: string
  symbol: string
  targetSymbol: string
  targetLine: number
  targetColumn: number
  external: string
  startLine: number
  endLine: number
  certainty: string
  terminal: boolean
  detail: string
}
export interface NativeExecutionEdge {
  ordinal: number
  from: string
  to: string
  kind: string
  label: string
  path: string
  startLine: number
  certainty: string
}
export interface NativeExecutionEntry {
  id: string
  kind: string
  label: string
  method: string
  route: string
  path: string
  symbol: string
  startLine: number
  endLine: number
  producerId: string
  producerVersion: string
  producerKind: string
  certainty: string
  nodes: Array<NativeExecutionNode>
  edges: Array<NativeExecutionEdge>
  diagnostics: Array<string>
}
export interface NativeFile {
  path: string
  lang: string
  loc: number
  bytes: number
  contentSha: string
  isTest: boolean
  /** False for files no grammar covers, or that were skipped as noise. */
  parsed: boolean
  symbols: Array<NativeSymbol>
  imports: Array<NativeImport>
  /** Uses of imported names, for symbol-level reference resolution. */
  refs: Array<NativeRef>
  /** Product-specific entry-to-effect facts extracted by bounded adapters. */
  executionEntries: Array<NativeExecutionEntry>
}
export interface NativeScan {
  files: Array<NativeFile>
  walkMs: number
  parseMs: number
}
export interface NativeSourceFile {
  path: string
  lang: string
  contentSha: string
  isTest: boolean
  content: string
}
export interface NativePathPolicy {
  language: string
  ignored: boolean
  noise: boolean
}
/** Walk and parse a repository. Both phases use every core, off the event loop. */
export declare function scanRepo(root: string): Promise<NativeScan>
/**
 * Read staged, unstaged, renamed, and untracked paths through Git porcelain.
 * Failure is returned as explicit degraded state so retrieval still works.
 */
export declare function gitChanges(root: string, isolatedConfig?: boolean | undefined | null): Promise<NativeGitChangeSet>
/** Classify a watcher path through the Rust-owned repository policy. */
export declare function sourcePathPolicy(path: string): NativePathPolicy
export interface NativeMatch {
  path: string
  line: number
  endLine: number
  /** The captured node's own text, trimmed for display. */
  text: string
  /** Which capture in the query matched, e.g. "@call". */
  capture: string
}
/**
 * Search by code shape rather than by text.
 *
 * A regex finds `catch` and cannot tell an empty handler from a careful one;
 * a tree-sitter query can, because it matches the parsed structure. This is
 * what makes "find every place we swallow an error" a question with an exact
 * answer instead of a grep and a lot of reading.
 *
 * The query is tree-sitter's own S-expression syntax, run against whichever
 * grammar each file needs.
 */
export declare function searchStructural(root: string, query: string, languages?: Array<string> | undefined | null, limit?: number | undefined | null, textFilter?: string | undefined | null): Promise<Array<NativeMatch>>
/** Read the bounded source inventory for deterministic content analyzers. */
export declare function readRepoFiles(root: string): Promise<Array<NativeSourceFile>>
/** One directly persisted SQLite connection, owned by the engine process. */
export declare class NativeDatabase {
  constructor(path: string, createIfMissing: boolean)
  /**
   * Validate, back up, and migrate a workspace store as one Rust-owned
   * storage lifecycle. The final schema and ordered steps are compiled into
   * this native owner; TypeScript never controls migration semantics.
   */
  migrate(projectRoot: string, backupDir: string): Promise<void>
  executeBatch(sql: string): void
  run(sql: string, paramsJson: string): void
  all(sql: string, paramsJson: string): string
  /**
   * Ranked lexical retrieval over deterministic facts and authored
   * knowledge. Query syntax is generated here so callers never pass raw
   * FTS expressions across the product boundary.
   */
  searchKnowledge(query: string, kindsJson: string, limit: number, memoryKind?: string | undefined | null): string
  /**
   * Rank task-relevant facts and one-hop graph evidence behind the existing
   * intent-oriented briefing boundary. Source reading and final byte packing
   * remain in the thin daemon adapter so repository containment has one
   * implementation, while retrieval policy and ordering live with SQLite.
   */
  taskContext(task: string, targetsJson: string, intent?: string | undefined | null, limit?: number | undefined | null, changesJson?: string | undefined | null): string
  /**
   * Query the bounded, evidence-backed execution graph assembled by native
   * framework adapters. Path enumeration remains inside the native storage
   * boundary and terminates on cycles and configured limits.
   */
  executionFlow(entryId?: string | undefined | null, maxPaths?: number | undefined | null, includeAssertions?: boolean | undefined | null): string
  close(): void
}
